export { createDaemon, type ElefantDaemon } from './daemon/create.ts'
export type { DaemonContext } from './daemon/context.ts'
export type { ElefantConfig, ProviderEntry } from './config/index.ts'
export { ConfigManager, loadConfig, loadConfigFromPath } from './config/index.ts'
export type { ConfigError, ConfigSourceLayer, ResolvedAgentConfig, AgentProfileOverride } from './config/index.ts'
export { createApp, type App } from './server/app.ts'
export type { AgentRun, RunContext } from './runs/types.ts'
export { RunRegistry } from './runs/registry.ts'
export type { Worktree, WorktreeError } from './worktree/types.ts'
